// wayfinder — Word/Excel/PDF 보고서 생성 및 내보내기.
// index.html의 dbGet/showToast/esc/br/AuditRules 등 전역을 그대로 쓴다
// (번들러 없는 구조라 로드 순서만 index.html보다 앞이면 된다).

const REPORT_TEMPLATES = {
  'report-type-1': "<!DOCTYPE html>\n<html lang=\"ko\">\n<head>\n<meta charset=\"UTF-8\">\n<title>{{audit.title}} 결과보고서</title>\n<style>\n  body{font-family:'맑은 고딕',Arial,sans-serif;font-size:10pt;margin:20mm;color:#172B4D}\n  h1{font-size:16pt;font-weight:bold;text-align:center;margin-bottom:4pt;color:#172B4D}\n  h2{font-size:12pt;font-weight:bold;margin-top:16pt;margin-bottom:4pt;color:#1a2332;border-bottom:1pt solid #1a2332;padding-bottom:3pt}\n  table{width:100%;border-collapse:collapse;margin-bottom:10pt}\n  th{background:#1a2332;color:#fff;padding:5pt 6pt;font-size:9pt;text-align:left}\n  td{border:0.5pt solid #ccc;padding:5pt 6pt;font-size:9pt;vertical-align:top}\n  .sum-table td:first-child{font-weight:bold;background:#f0f4f8;width:30%}\n  .result{font-weight:bold;padding:2pt 6pt;border-radius:3pt;display:inline-block}\n  .ok,.yes{color:#1a7c3e;background:#eafaf1}\n  .ng,.no{color:#c0392b;background:#fdecea}\n  .na{color:#7f8c8d;background:#f4f4f4}\n  .obs{color:#e67e22;background:#fef5e7}\n  .footer{font-size:8pt;color:#888;text-align:right;margin-top:20pt;border-top:0.5pt solid #ccc;padding-top:6pt}\n</style>\n</head>\n<body>\n<h1>심사 점검표 결과보고서</h1>\n<table class=\"sum-table\">\n  <tr><td>심사명</td><td>{{audit.title}}</td><td>심사일</td><td>{{audit.date}}</td></tr>\n  <tr><td>심사원</td><td>{{audit.auditor}}</td><td>피심사 부서</td><td>{{audit.dept}}</td></tr>\n  <tr><td>전체 항목</td><td>{{summary.total}}건</td><td>작성일</td><td>{{generated.date}}</td></tr>\n</table>\n\n<h2>심사 결과 요약</h2>\n<table>\n  <tr><th>구분</th><th>건수</th><th>비율</th><th>비고</th></tr>\n  {{summary.rows}}\n  <tr><td><strong>합계</strong></td><td>{{summary.total}}건</td><td>100%</td><td></td></tr>\n</table>\n\n{{sections}}\n\n{{ng.section}}\n\n<div class=\"footer\">Generated by 심사 점검표 앱 · {{generated.datetime}}</div>\n</body>\n</html>\n",
  'report-type-2': "<!DOCTYPE html>\n<html lang=\"ko\">\n<head>\n<meta charset=\"UTF-8\">\n<title>{{audit.title}} 현장탑승심사표</title>\n<style>\n  @page { size: A4 portrait; margin: 14mm 12mm; }\n  * { box-sizing: border-box; }\n  body { margin: 0; background: #ffffff; color: #000000; font-family: \"Malgun Gothic\", \"맑은 고딕\", Arial, sans-serif; font-size: 9pt; line-height: 1.35; }\n  .print-page { width: 186mm; margin: 0 auto; background: #ffffff; }\n  table { border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; }\n  td, th { mso-line-height-rule: exactly; }\n  .report-meta { width: 100%; table-layout: fixed; border-collapse: collapse; margin-bottom: 8px; }\n  .report-meta td { border: 1px solid #000; padding: 4px 6px; font-size: 8.5pt; vertical-align: middle; }\n  .report-meta .label { background: #d9d9d9; font-weight: 700; width: 18%; text-align: center; }\n  .field-block { width: 100%; margin-bottom: 10px; page-break-inside: avoid; break-inside: avoid; }\n  .top-table, .maturity-table, .comment-table, .result-table { width: 100%; table-layout: fixed; border-collapse: collapse; }\n  .top-table th, .top-table td,\n  .maturity-table th, .maturity-table td,\n  .comment-table td, .result-table td { border: 1px solid #000000; padding: 4px 6px; vertical-align: top; word-break: keep-all; overflow-wrap: break-word; }\n  .top-table { border: 1.5px solid #000; }\n  .top-table th { background: #d9d9d9; text-align: center; font-family: \"Times New Roman\", \"Malgun Gothic\", serif; font-size: 12pt; font-weight: 700; line-height: 1.15; vertical-align: middle; }\n  .section-title { font-size: 10.5pt; font-weight: 700; text-align: left; padding: 5px 6px !important; }\n  .item-no { text-align: center; vertical-align: middle !important; font-size: 10pt; font-weight: 700; }\n  .requirement { font-size: 9.5pt; min-height: 18mm; }\n  .refs, .external-ref { font-size: 9pt; line-height: 1.35; }\n  .external-ref { text-align: center; vertical-align: middle !important; }\n  .maturity-table { border-left: 1.5px solid #000; border-right: 1.5px solid #000; }\n  .satisfaction-cell { background: #d9d9d9; text-align: center; vertical-align: middle !important; font-family: \"Times New Roman\", \"Malgun Gothic\", serif; font-size: 12pt; font-weight: 700; line-height: 1.15; }\n  .maturity-head, .consider-head { background: #d9d9d9; text-align: center; vertical-align: middle !important; font-weight: 700; }\n  .maturity-head { font-family: \"Times New Roman\", \"Malgun Gothic\", serif; font-size: 11pt; line-height: 1.15; }\n  .consider-head { font-size: 10pt; }\n  .maturity-label { vertical-align: middle !important; font-family: \"Times New Roman\", \"Malgun Gothic\", serif; font-size: 10.5pt; font-weight: 700; }\n  .consider-text { font-size: 8.8pt; line-height: 1.35; }\n  .consider-title { font-weight: 700; margin-bottom: 2px; }\n  .comment-table { border-left: 1.5px solid #000; border-right: 1.5px solid #000; }\n  .comment-label { width: 70mm; background: #d9d9d9; text-align: center; vertical-align: middle !important; font-family: \"Times New Roman\", \"Malgun Gothic\", serif; font-size: 11pt; font-weight: 700; }\n  .comment-box { height: 11mm; white-space: pre-wrap; }\n  .result-table { border: 1.5px solid #000; border-top: 0; }\n  .result-row-label { height: 10mm; font-family: \"Times New Roman\", \"Malgun Gothic\", serif; font-size: 11pt; font-weight: 700; vertical-align: middle !important; }\n  .checkbox { font-family: \"Times New Roman\", \"Malgun Gothic\", serif; font-weight: 700; white-space: nowrap; }\n  .checkbox::before { content: \"□ \"; font-family: \"Malgun Gothic\", Arial, sans-serif; font-weight: 400; }\n  .selected::before { content: \"■ \"; }\n  .print-only-note { margin-top: 8px; color: #666666; font-size: 8pt; text-align: right; }\n  @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } .print-page { width: 100%; } .print-only-note { display: none; } }\n</style>\n</head>\n<body>\n  <div class=\"print-page\">\n    <table class=\"report-meta\">\n      <tr><td class=\"label\">심사명</td><td>{{audit.title}}</td><td class=\"label\">심사일</td><td>{{audit.date}}</td></tr>\n      <tr><td class=\"label\">심사원</td><td>{{audit.auditor}}</td><td class=\"label\">피심사 부서</td><td>{{audit.dept}}</td></tr>\n    </table>\n    {{fieldAuditItems}}\n    <div class=\"print-only-note\">Generated by 심사 점검표 앱 · {{generated.datetime}}</div>\n  </div>\n</body>\n</html>\n"
};

// ═══════════════════════════════════════════════
//  Export: Excel
// ═══════════════════════════════════════════════
function safeDownloadName(value, fallback){
  const name = String(value || '').replace(/[\\/:*?"<>|]/g, '_').replace(/\s+/g, ' ').trim();
  return name || fallback;
}

async function exportExcel(id){
  const audit = await dbGet('audits', id);
  if(!audit){ showToast('심사를 불러올 수 없습니다'); return; }

  const wb = XLSX.utils.book_new();

  // Summary sheet
  const summary = getAuditSummary(audit);
  const items = getAuditItems(audit);

  const sumData=[
    ['심사 요약'],
    [],
    ['심사명', audit.title],
    ['심사일', audit.date],
    ['심사원', audit.auditor],
    ['피심사 부서', audit.dept],
    ['작성일', new Date().toLocaleDateString('ko-KR')],
    [],
    ['구분','건수','비율'],
    ['YES', summary.yes, getResultPercent(summary.yes, summary.total)],
    ['NO', summary.no, getResultPercent(summary.no, summary.total)],
    ['N/A', summary.na, getResultPercent(summary.na, summary.total)],
    ['OBS', summary.obs, getResultPercent(summary.obs, summary.total)],
    ['합계', summary.total, '100%'],
  ];
  const wsSum = XLSX.utils.aoa_to_sheet(sumData);
  wsSum['!cols']=[{wch:20},{wch:12},{wch:10}];
  XLSX.utils.book_append_sheet(wb, wsSum, '요약');

  // Detail sheet
  const detailData=[['섹션','항목번호','점검 항목','참조규정','결과','비고']];
  items.forEach(item=>{
    detailData.push([item.section||'',item.ref||'',item.question||'',item.refStd||'',normalizeResultValue(item.result)||'',item.note||'']);
  });
  const wsDetail = XLSX.utils.aoa_to_sheet(detailData);
  wsDetail['!cols']=[{wch:16},{wch:12},{wch:50},{wch:20},{wch:8},{wch:40}];
  XLSX.utils.book_append_sheet(wb, wsDetail, '점검결과');

  // NG sheet
  const ngItems = items.filter(i=>normalizeResultValue(i.result)===RESULT_VALUE.NO);
  if(ngItems.length>0){
    const ngData=[['섹션','항목번호','부적합 내용','세부사항']];
    ngItems.forEach(item=>{
      ngData.push([item.section||'',item.ref||'',item.question||'',item.note||'']);
    });
    const wsNG = XLSX.utils.aoa_to_sheet(ngData);
    wsNG['!cols']=[{wch:16},{wch:12},{wch:50},{wch:40}];
    XLSX.utils.book_append_sheet(wb, wsNG, '부적합사항');
  }

  const fname = `${safeDownloadName(audit.title, '심사결과')}_${safeDownloadName(audit.date, '결과')}.xlsx`;
  XLSX.writeFile(wb, fname);
  showToast('Excel 파일 저장됨');
}


function getTopsChecklistHeaders(){
  // Matches the uploaded TOPS AUDIT Checklist bulk-registration template.
  return ['ITEM','ITEM_NO','REQUIREMENT','INTERNAL_REF','EXTERNAL_REF','GUIDANCE','S','U/S','N/A','N/O','OBS','Comments'];
}

function getTopsResultMarks(result){
  const r = normalizeResultValue(result);
  return {
    s: r === 'YES' ? 'Y' : '',
    us: r === 'NO' ? 'Y' : '',
    na: r === 'N/A' ? 'Y' : '',
    no: r === 'N/O' ? 'Y' : '',
    obs: r === 'OBS' ? 'Y' : ''
  };
}

function getTopsGuidanceText(item){
  return String(
    item?.guidance ??
    item?.guidanceText ??
    item?.['GUIDANCE'] ??
    ''
  ).trim();
}

function buildTopsChecklistRows(audit){
  const rows = [getTopsChecklistHeaders()];
  getAuditItems(audit).forEach((item, index)=>{
    const marks = getTopsResultMarks(item.result);
    rows.push([
      item.section || '',
      item.ref || String(index + 1),
      item.question || '',
      item.refStd || '',
      item.externalRef || item.external || '',
      getTopsGuidanceText(item),
      marks.s,
      marks.us,
      marks.na,
      marks.no,
      marks.obs,
      item.note || ''
    ]);
  });
  return rows;
}

async function exportTopsChecklistExcel(id){
  const audit = await dbGet('audits', id);
  if(!audit){ showToast('심사를 불러올 수 없습니다'); return; }

  const rows = buildTopsChecklistRows(audit);
  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.aoa_to_sheet(rows);

  ws['!cols'] = [
    {wch:18}, // ITEM
    {wch:12}, // ITEM_NO
    {wch:56}, // REQUIREMENT
    {wch:28}, // INTERNAL_REF
    {wch:28}, // EXTERNAL_REF
    {wch:38}, // GUIDANCE
    {wch:8},  // S
    {wch:8},  // U/S
    {wch:8},  // N/A
    {wch:8},  // N/O
    {wch:8},  // OBS
    {wch:40}  // Comments
  ];
  ws['!autofilter'] = { ref: `A1:L${Math.max(rows.length, 1)}` };

  XLSX.utils.book_append_sheet(wb, ws, 'CheckList');

  const safeTitle = String(audit.title || 'TOPS_AUDIT_Checklist').replace(/[\\/:*?"<>|]/g, '_');
  const safeDate = String(audit.date || new Date().toISOString().slice(0,10)).replace(/[\\/:*?"<>|]/g, '_');
  XLSX.writeFile(wb, `${safeTitle}_${safeDate}_TOPS_CheckList.xlsx`);
  showToast('TOPS Checklist Excel 저장됨');
}

// ═══════════════════════════════════════════════
//  Export: Word (HTML → .doc trick, wide support)
// ═══════════════════════════════════════════════
function escapeRegex(value){
  return String(value).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function replaceTemplateTokens(template, values){
  let output = template;
  Object.entries(values).forEach(([key,value])=>{
    output = output.replace(new RegExp(escapeRegex('{{'+key+'}}'), 'g'), value == null ? '' : String(value));
  });
  return output;
}

async function getAuditReportTemplateType(audit){
  // 1) First inspect the audit record itself.
  const auditInferred = inferReportTemplateType(audit);
  if(auditInferred === 'report-type-2') return 'report-type-2';

  // 2) Existing audits may have been created before templateName/reportTemplate was stored.
  //    In that case, resolve the original checklist template by templateId and infer from its filename/name.
  if(audit?.templateId){
    try{
      const tpl = await getNormalizedTemplate(Number(audit.templateId));
      const tplInferred = inferReportTemplateType(tpl);
      if(tplInferred === 'report-type-2') return 'report-type-2';
    } catch(e){
      appWarn('보고서 양식 판별용 점검표 조회 실패:', e);
    }
  }

  // 3) Fall back to the value saved in the audit, then default to type-1.
  return audit?.reportTemplate || auditInferred || 'report-type-1';
}

function loadReportTemplate(type){
  const template = REPORT_TEMPLATES[type] || REPORT_TEMPLATES['report-type-1'];
  if(!template) throw new Error('보고서 양식이 등록되어 있지 않습니다.');
  return template;
}

function getResultSummary(audit){
  // Compatibility alias for existing report-generation code.
  return getAuditSummary(audit);
}

function renderSummaryRows(audit){
  const {total, ok, ng, na, obs} = getResultSummary(audit);
  return [['YES','적합',ok],['NO','부적합',ng],['OBS','관찰사항',obs],['N/A','해당없음',na]].map(([r,l,n])=>`
<tr><td><span class="result ${r.toLowerCase()}">${r}</span> ${l}</td><td>${n}건</td><td>${total?Math.round(n/total*100):0}%</td><td></td></tr>`).join('');
}

function groupAuditItemsBySection(audit){
  const sections = {};
  (audit.items || []).forEach(item=>{
    const sec = item.section || '일반';
    if(!sections[sec]) sections[sec] = [];
    sections[sec].push(item);
  });
  return sections;
}

function renderType1Sections(audit){
  const sections = groupAuditItemsBySection(audit);
  return Object.entries(sections).map(([sec,items])=>`
<h2>${esc(sec)}</h2>
<table><tr><th style="width:10%">번호</th><th style="width:40%">점검 항목</th><th style="width:15%">참조규정</th><th style="width:8%">결과</th><th style="width:27%">비고</th></tr>
${items.map(item=>`<tr>
  <td>${esc(item.ref||'')}</td>
  <td>${esc(item.question)}</td>
  <td>${esc(item.refStd||'')}</td>
  <td>${normalizeResultValue(item.result)?`<span class="result ${resultCssClass(item.result)}">${normalizeResultValue(item.result)}</span>`:'-'}</td>
  <td>${esc(item.note||'')}</td>
</tr>`).join('')}</table>`).join('');
}

function renderType1NgSection(audit){
  const ngItems = (audit.items || []).filter(i=>normalizeResultValue(i.result)==='NO');
  if(ngItems.length === 0) return '';
  return `<h2>부적합 사항 목록</h2>
<table><tr><th style="width:10%">번호</th><th style="width:45%">부적합 내용</th><th style="width:45%">세부 사항</th></tr>
${ngItems.map(item=>`<tr>
  <td>${esc(item.ref||'')}</td>
  <td>${esc(item.question)}</td>
  <td>${esc(item.note||'')}</td>
</tr>`).join('')}</table>`;
}

function resultSelected(item, result){
  return normalizeResultValue(item.result) === result ? ' selected' : '';
}

function renderFieldAuditItem(item, index){
  const sectionTitle = esc(item.section || '일반');
  const ref = esc(item.ref || String(index + 1));
  const question = br(item.question || '');
  const internalRef = br(item.refStd || '');
  const externalRef = br(item.externalRef || item.external || '');
  const note = br(item.note || '');
  const maturityLevels = AuditRules.MATURITY_LEVELS;

  // Type-2 Word compatibility rule:
  // Each checklist item is rendered as small fixed-width tables to keep Word/PDF layout stable.
  return `<div class="field-block">
    <table class="top-table">
      <colgroup>
        <col style="width:14mm"><col style="width:88mm"><col style="width:42mm"><col style="width:42mm">
      </colgroup>
      <thead>
        <tr>
          <th>No.</th>
          <th>Check<br>Requirements</th>
          <th>Internal<br>Ref.</th>
          <th>External<br>Ref.</th>
        </tr>
      </thead>
      <tbody>
        <tr><td colspan="4" class="section-title">${sectionTitle}</td></tr>
        <tr>
          <td class="item-no">${ref}</td>
          <td class="requirement">${question}</td>
          <td class="refs">${internalRef}</td>
          <td class="external-ref">${externalRef}</td>
        </tr>
      </tbody>
    </table>

    <table class="result-table">
      <colgroup><col style="width:46.5mm"><col style="width:46.5mm"><col style="width:46.5mm"><col style="width:46.5mm"></colgroup>
      <tbody>
        <tr>
          <td class="result-row-label"><span class="checkbox${resultSelected(item,'YES')}">YES</span></td>
          <td class="result-row-label"><span class="checkbox${resultSelected(item,'NO')}">NO</span></td>
          <td class="result-row-label"><span class="checkbox${resultSelected(item,'OBS')}">OBS</span></td>
          <td class="result-row-label"><span class="checkbox${resultSelected(item,'N/A')}">N/A</span></td>
        </tr>
      </tbody>
    </table>

    <table class="maturity-table">
      <colgroup>
        <col style="width:36mm"><col style="width:34mm"><col style="width:116mm">
      </colgroup>
      <tbody>
        <tr>
          <td rowspan="5" class="satisfaction-cell">Maturity<br>Assessment</td>
          <td class="maturity-head">Maturity<br>Level</td>
          <td class="consider-head">요구조건 / 판단기준</td>
        </tr>
        ${maturityLevels.map(level=>{
          const c = getMaturityConsideration(item, level);
          return `<tr>
            <td class="maturity-label"><span class="checkbox${item.maturity === level ? ' selected' : ''}">${level}</span></td>
            <td class="consider-text"><div class="consider-title">${esc(c.title)}</div>${esc(c.body)}</td>
          </tr>`;
        }).join('')}
      </tbody>
    </table>

    <table class="comment-table">
      <colgroup><col style="width:70mm"><col style="width:116mm"></colgroup>
      <tbody><tr><td class="comment-label">Comment(s)</td><td class="comment-box">${note}</td></tr></tbody>
    </table>
  </div>`;
}
function renderFieldAuditItems(audit){
  return (audit.items || []).map((item,index)=>renderFieldAuditItem(item,index)).join('');
}

function fillReportTemplate(template, audit, type){
  const summary = getResultSummary(audit);
  const now = new Date();
  const values = {
    'audit.title': esc(audit.title || ''),
    'audit.date': esc(audit.date || ''),
    'audit.auditor': esc(audit.auditor || ''),
    'audit.dept': esc(audit.dept || ''),
    'summary.total': summary.total,
    'summary.rows': renderSummaryRows(audit),
    'sections': renderType1Sections(audit),
    'ng.section': renderType1NgSection(audit),
    'fieldAuditItems': renderFieldAuditItems(audit),
    'generated.date': now.toLocaleDateString('ko-KR'),
    'generated.datetime': now.toLocaleString('ko-KR')
  };
  return replaceTemplateTokens(template, values);
}

async function exportWord(id){
  const audit = await dbGet('audits', id);
  if(!audit){ showToast('심사를 불러올 수 없습니다'); return; }

  try{
    const type = await getAuditReportTemplateType(audit);
    const template = await loadReportTemplate(type);
    const html = fillReportTemplate(template, audit, type);
    const blob = new Blob(['\ufeff' + html], {type:'application/msword;charset=utf-8'});
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${safeDownloadName(audit.title, '심사결과')}_${safeDownloadName(audit.date, '결과')}_${safeDownloadName(getReportTemplateLabel(type), '보고서')}.doc`;
    a.click();
    URL.revokeObjectURL(url);
    showToast('Word 파일 저장됨');
  } catch(err){
    appError('Word 출력 실패:', err);
    showToast(err.message || 'Word 파일을 만들 수 없습니다');
  }
}

// ═══════════════════════════════════════════════
//  Export: PDF (print)
// ═══════════════════════════════════════════════
async function exportPDF(id){
  const audit = await dbGet('audits', id);
  if(!audit){ showToast('심사를 불러올 수 없습니다'); return; }

  const w = window.open('', '_blank');
  if(!w){ showToast('팝업 차단을 해제한 뒤 다시 시도하세요'); return; }

  try{
    const type = await getAuditReportTemplateType(audit);
    const template = loadReportTemplate(type);
    const html = fillReportTemplate(template, audit, type);
    const printableHtml = html
      .replace('</head>', `<style>
        .pdf-print-action{position:fixed;top:10px;right:10px;z-index:9999;padding:8px 16px;background:#1868DB;color:#fff;border:0;border-radius:6px;cursor:pointer;font:600 13px "Malgun Gothic",sans-serif}
        @media print{.pdf-print-action{display:none!important}}
      </style></head>`)
      .replace('</body>', `<button type="button" class="pdf-print-action" onclick="window.print()">인쇄/PDF 저장</button></body>`);

    w.document.open();
    w.document.write(printableHtml);
    w.document.close();
    w.focus();
    showToast('인쇄 창에서 PDF로 저장하세요');
  } catch(err){
    w.close();
    appError('PDF 출력 실패:', err);
    showToast(err.message || 'PDF 출력 화면을 만들 수 없습니다');
  }
}
